### ISSUE TITLE
function getRagResponse evolution requests

### ISSUE THREAD

**Issue by cocquerel** [SAP-samples/cap-llm-plugin-samples#4]
Thanks a lot for this CAP LLM Plugin, it really simplifies the development.
I would suggest few improvements for function getRagResponse:

- I would prefer the search for similar vectors to be based on the full user chat history and not the last question only. Indeed, let suppose the first question is "What is XXXX ?" and the second is "Where to find it ?". If you only take into account the last question, you will not consider that "it" is referring to "XXXX" and the result is not appropriate.

- I would have preferred that the getRagResponse function to send back in additionalContents, not only the columns score and pageContent but also the column pagemetadata. In my use case, it contains the source URL to the origin documents and I wanted to provide those links to the user together with LLM answer.

 - last point would be to exclude from the vector search, the page contents that were already provided  in previous messages of the conversation. I would prefer to provide the LLM with additional context information instead of repeating the same.

**Comment by feng-lia** [comment]
1. we do not want to combine chat history together with every user query since we would like to provide flexibility to developers working on other scenarios too. If you do need to pass chat history, put it to context parameter.
2. you can use the new method getRagResponseWithConfig which gives you additional contents in its response.
3. we would like to have a certain level of granularity for our plugin api so that it can be used for more scenarios instead of a specific one.
